stages:
  - sonar
image: node:latest
cache:
  paths:
    - node_modules/
before_script:
  - npm install
sonar-scan:
  stage: sonar
  image: devops-hub.tutorabc.com.cn/library/sonar-scanner-cpp-python:2.1.1
  variables:
    SONAR_URL: http://sonar.devops.tutorabc.com.cn
    SONAR_PROJECT_VERSION: $CI_BUILD_REF
    SONAR_ANALYSIS_MODE: publish
  before_script:
    - npm install
  script:
    - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh
